# Generated by Django 3.0.7 on 2020-07-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200705_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='business_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
