# Generated by Django 3.0.7 on 2020-09-20 11:52

from django.db import migrations


def update_paid_invoices(apps, schema_editor):
    # Invoice = apps.get_model('payments', 'Invoice')
    # PayPalIPN = apps.get_model('ipn', 'PayPalIPN')
    # for invoice in Invoice.objects.all():
    #     if invoice.transaction_id:
    #         ipn = PayPalIPN.objects.filter(txn_id=invoice.transaction_id, payment_status='Completed').first()
    #         invoice.date_paid = ipn.payment_date
    #         invoice.paid = True
    #         invoice.save()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_adding_stripe_20200921_1614'),
    ]

    operations = [
        migrations.RunPython(
            update_paid_invoices, reverse_code=migrations.RunPython.noop
        )
    ]
