# Generated by Django 3.0.10 on 2020-09-22 16:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_data_migration_update_paid_invoices_20200920_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('client_secret', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Invoice')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Seller')),
            ],
        ),
    ]
