# Generated by Django 3.0.7 on 2020-09-20 11:52

from django.db import migrations


def update_paid_invoices(apps, schema_editor):
    Invoice = apps.get_model('payments', 'Invoice')
    for invoice in Invoice.objects.all():
        if invoice.transaction_id:
            invoice.paid = True
            invoice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20200920_1140'),
    ]

    operations = [
        migrations.RunPython(
            update_paid_invoices, reverse_code=migrations.RunPython.noop
        )
    ]
