# Generated by Django 3.0.10 on 2020-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_stripepaymentintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='voucher_code',
            field=models.CharField(blank=True, help_text='Voucher applied to invoice total', max_length=255, null=True),
        ),
    ]
