# Generated by Django 4.1.1 on 2022-10-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_stripepaymentintent_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="final_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
