language: python

python:
  - "3.7"

addons:
  postgresql: "9.5"

env: >
  SECRET_KEY=dummy_secret
  EMAIL_HOST_PASSWORD=dummy_password
  DATABASE_URL=postgres://postgres@localhost/travis_ci_test
  DEFAULT_PAYPAL_EMAIL=dummy-email@hotmail.com
  PAYPAL_TEST=True
  LOG_FOLDER=log_folder
  TRAVIS=True
  HEROKU=False
  SEND_ALL_STUDIO_EMAILS=True
  INVOICE_KEY=dummy_key
  PAYPAL_IDENTITY_TOKEN=dummy_token
  CHECKOUT_METHOD=stripe
  STRIPE_PUBLISHABLE_KEY=dummy_key
  STRIPE_SECRET_KEY=dummy_secret
  STRIPE_CONNECT_CLIENT_ID=dummy_client_id
  STRIPE_ENDPOINT_SECRET=dummy_endpoint_secret


install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install psycopg2

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate

script:
  - pytest --cov-config=.coveragerc --cov=.

after_success:
  coveralls
