# Generated by Django 3.0.7 on 2020-06-28 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.DecimalField(decimal_places=1, max_digits=100)),
                ('terms_accepted', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_archived', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CookiePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('version', models.DecimalField(decimal_places=1, max_digits=100, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Cookie Policies',
            },
        ),
        migrations.CreateModel(
            name='DataPrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('version', models.DecimalField(decimal_places=1, max_digits=100, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Data Privacy Policies',
            },
        ),
        migrations.CreateModel(
            name='DisclaimerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer_terms', models.TextField()),
                ('version', models.DecimalField(decimal_places=1, max_digits=100, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_draft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NonRegisteredDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.DecimalField(decimal_places=1, max_digits=100)),
                ('terms_accepted', models.BooleanField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_name', models.CharField(max_length=255, verbose_name='name')),
                ('emergency_contact_relationship', models.CharField(max_length=255, verbose_name='relationship')),
                ('emergency_contact_phone', models.CharField(max_length=255, verbose_name='contact number')),
                ('event_date', models.DateField()),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Event disclaimer',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_name', models.CharField(max_length=255, verbose_name='name')),
                ('emergency_contact_relationship', models.CharField(max_length=255, verbose_name='relationship')),
                ('emergency_contact_phone', models.CharField(max_length=255, verbose_name='contact number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.DecimalField(decimal_places=1, max_digits=100)),
                ('terms_accepted', models.BooleanField()),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_disclaimer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignedDataPrivacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.DecimalField(decimal_places=1, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_privacy_agreement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signed Data Privacy Agreement',
                'unique_together': {('user', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='onlinedisclaimer',
            index=models.Index(fields=['user'], name='accounts_on_user_id_03aad6_idx'),
        ),
    ]
