# Generated by Django 3.0.7 on 2020-06-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200628_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonregistereddisclaimer',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
