# Generated by Django 3.0.7 on 2020-07-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200702_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student',
            field=models.BooleanField(default=True),
        ),
    ]
