# Generated by Django 3.0.7 on 2020-07-07 06:40

from django.db import migrations
import dynamic_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200706_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='health_questionnaire_responses',
            field=dynamic_forms.models.ResponseField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disclaimercontent',
            name='form',
            field=dynamic_forms.models.FormField(default=[], verbose_name='health questionnaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonregistereddisclaimer',
            name='health_questionnaire_responses',
            field=dynamic_forms.models.ResponseField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinedisclaimer',
            name='health_questionnaire_responses',
            field=dynamic_forms.models.ResponseField(default=[]),
            preserve_default=False,
        ),
    ]
