# Generated by Django 3.0.7 on 2020-07-07 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200707_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
