# Generated by Django 3.0.7 on 2020-07-08 06:57

from django.db import migrations
import dynamic_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200707_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclaimercontent',
            name='form',
            field=dynamic_forms.models.FormField(blank=True, null=True, verbose_name='health questionnaire'),
        ),
    ]
