# Generated by Django 3.0.7 on 2020-08-28 10:44

from django.db import migrations, models
import dynamic_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200803_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclaimercontent',
            name='form_info',
            field=models.TextField(blank=True, help_text='Optional text to display after the questionnaire questions', null=True, verbose_name='Additional questionnaire info'),
        ),
        migrations.AddField(
            model_name='disclaimercontent',
            name='form_title',
            field=models.CharField(default='Health Questionnaire', max_length=255),
        ),
        migrations.AlterField(
            model_name='disclaimercontent',
            name='form',
            field=dynamic_forms.models.FormField(blank=True, null=True, verbose_name='Questionnaire questions'),
        ),
    ]
