# Generated by Django 3.0.7 on 2020-09-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200828_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
