# Generated by Django 4.1.2 on 2023-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20210414_2121"),
    ]

    operations = [
        migrations.AddField(
            model_name="childuserprofile",
            name="pronouns",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pronouns",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
