# Generated by Django 3.0.7 on 2020-07-01 08:50

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=40, populate_from=['name', 'course_type'], unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'course_type')},
        ),
    ]
