# Generated by Django 3.0.7 on 2020-06-29 11:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Course'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default=90, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=40, populate_from=['name', 'start'], unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True),
        ),
    ]
