# Generated by Django 3.0.7 on 2020-07-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200701_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='email_studio_when_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='booking.Course'),
        ),
    ]
