# Generated by Django 3.0.7 on 2020-07-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200701_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='email_studio_when_booked',
        ),
        migrations.RemoveField(
            model_name='event',
            name='allow_booking_cancellation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cancellation_period',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='email_studio_when_booked',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_online',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='allow_booking_cancellation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='cancellation_period',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='contact_email',
            field=models.EmailField(default='freedomofflightaerial@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='email_studio_when_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
