# Generated by Django 3.0.7 on 2020-06-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200629_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='default',
            field=models.BooleanField(default=False, help_text='Set one track to default to use as landing page for site'),
        ),
    ]
