# Generated by Django 3.0.7 on 2020-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200702_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseblockconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
