# Generated by Django 3.0.7 on 2020-07-03 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0005_baseblockconfig_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedblockvoucher',
            name='block_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usedblockvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_vouchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
