# Generated by Django 3.0.7 on 2020-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200703_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockvoucher',
            name='block_types',
            field=models.ManyToManyField(blank=True, to='booking.DropInBlockConfig'),
        ),
        migrations.AlterField(
            model_name='blockvoucher',
            name='course_types',
            field=models.ManyToManyField(blank=True, to='booking.CourseBlockConfig'),
        ),
    ]
