# Generated by Django 3.0.7 on 2020-07-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200703_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftvouchertype',
            old_name='course_block_type',
            new_name='course_block_config',
        ),
        migrations.RenameField(
            model_name='giftvouchertype',
            old_name='dropin_block_type',
            new_name='dropin_block_config',
        ),
        migrations.AddField(
            model_name='block',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.BlockVoucher'),
        ),
    ]
