# Generated by Django 3.0.7 on 2020-07-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20200703_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='booking.BlockVoucher'),
        ),
        migrations.DeleteModel(
            name='UsedBlockVoucher',
        ),
    ]
