# Generated by Django 3.0.7 on 2020-07-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('booking', '0010_auto_20200703_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Invoice'),
        ),
    ]
