# Generated by Django 3.0.7 on 2020-07-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200705_0850'),
        ('booking', '0011_block_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='payments.Invoice'),
        ),
    ]
