# Generated by Django 3.0.7 on 2020-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20200705_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseblockconfig',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=4, help_text='Number of weeks until block expires (from first use)', null=True),
        ),
    ]
