# Generated by Django 3.0.7 on 2020-07-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20200705_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
