# Generated by Django 3.0.7 on 2020-07-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_course_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_on_site',
            field=models.BooleanField(default=False),
        ),
    ]
