# Generated by Django 3.0.7 on 2020-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_course_show_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='label',
            field=models.CharField(default='class', help_text='How an instance of this event type will be referred to, e.g. "class", "workshop"', max_length=255),
        ),
        migrations.AlterField(
            model_name='basevoucher',
            name='max_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum times this voucher can be used by a single user', null=True, verbose_name='Maximum uses per user'),
        ),
    ]
