# Generated by Django 3.0.7 on 2020-07-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20200715_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_participants',
            field=models.PositiveIntegerField(help_text='Overrides any value set on individual linked events'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='A short identifier that will be displayed to users on the event list.  ', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='show_on_site',
            field=models.BooleanField(default=False, help_text='Overrides any value set on individual linked events'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
