# Generated by Django 3.0.7 on 2020-07-21 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20200716_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='booking.Track'),
        ),
    ]
