# Generated by Django 3.0.7 on 2020-07-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_eventtype_plural_suffix'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursetype',
            unique_together={('event_type', 'number_of_events')},
        ),
    ]
