# Generated by Django 3.0.7 on 2020-08-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20200803_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='course_block_config',
        ),
        migrations.RemoveField(
            model_name='block',
            name='dropin_block_config',
        ),
        migrations.AddField(
            model_name='blockvoucher',
            name='block_configs',
            field=models.ManyToManyField(blank=True, to='booking.BlockConfig'),
        ),
        migrations.AddField(
            model_name='course',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.EventType'),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_events',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='giftvouchertype',
            name='block_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_vouchers', to='booking.BlockConfig'),
        ),
        migrations.AlterField(
            model_name='giftvouchertype',
            name='dropin_block_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropin_gift_vouchers', to='booking.BlockConfig'),
        ),
    ]
