# Generated by Django 3.0.7 on 2020-08-03 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_auto_20200803_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.BlockConfig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.EventType'),
            preserve_default=False,
        ),
    ]
