# Generated by Django 3.0.7 on 2020-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20200803_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockvoucher',
            name='block_configs',
            field=models.ManyToManyField(to='booking.BlockConfig'),
        ),
    ]
