# Generated by Django 3.0.7 on 2020-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20200803_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='booking_restriction',
            field=models.PositiveIntegerField(default=15, help_text='Time (minutes) to prevent booking prior to event start. Set to 0 to allow unrestricted booking up to the event start time'),
        ),
    ]
