# Generated by Django 3.0.7 on 2020-08-12 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0028_auto_20200811_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('paused', 'paused'), ('cancelled', 'cancelled')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.PositiveIntegerField(default=1, help_text='How long does the subscription run for (weeks/months) until renewal')),
                ('duration_units', models.CharField(choices=[('weeks', 'weeks'), ('months', 'months')], default='months', max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recurrence', models.BooleanField(default=True, help_text='Subscription automatically renews and bills students')),
                ('recur_options', models.CharField(choices=[('start_date', 'Recur from the specified start date'), ('signup_date', 'Recur from the date students sign up')], help_text='Control when subscription renews and bills.  Choose start date to run the subscription for a set time period (e.g. from the 1st of each month).  Choose sign up date to have the subscription renew for each student from the date they first signed up.', max_length=255)),
                ('purchasable', models.BooleanField(default=True, help_text='Visible on site and available to purchase')),
                ('status', models.CharField(choices=[('active', 'active'), ('paused', 'paused'), ('cancelled', 'cancelled')], default='active', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='BaseBlockConfig',
        ),
        migrations.AddField(
            model_name='purchasedsubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Subscription'),
        ),
        migrations.AddField(
            model_name='purchasedsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
