# Generated by Django 3.0.7 on 2020-08-21 15:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_subscriptionconfig_include_no_shows_in_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invoiced_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_show',
            field=models.BooleanField(default=False, help_text='Student booked but did not attend, or cancelled after the allowed cancellation period'),
        ),
        migrations.AlterField(
            model_name='subscriptionconfig',
            name='bookable_event_types',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionconfig',
            name='partial_purchase_allowed',
            field=models.BooleanField(default=False, help_text='For subscriptions with a specific start date, allow purchase of the current subscription period at a reduced price after the first week.'),
        ),
    ]
