# Generated by Django 3.0.7 on 2020-08-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_auto_20200821_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionconfig',
            name='current_subscriber_info',
            field=models.TextField(blank=True, help_text='Information that will be displayed in the details for active subscriptions only.  Use this for information that may change with each subscription period, e.g. passwords to content on other sites', null=True),
        ),
    ]
