# Generated by Django 3.0.7 on 2020-08-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_subscriptionconfig_current_subscriber_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('event__start',), 'permissions': (('can_view_registers', 'Can view registers'),)},
        ),
    ]
