# Generated by Django 3.0.7 on 2020-08-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_auto_20200827_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevoucher',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount as an exact amount off the purchased item cost', max_digits=6, null=True, verbose_name='Exact amount discount'),
        ),
        migrations.AlterField(
            model_name='basevoucher',
            name='discount',
            field=models.PositiveIntegerField(blank=True, help_text='Discount value as a % of the purchased item cost. Enter a number between 1 and 100', null=True, verbose_name='Percentage discount'),
        ),
    ]
