# Generated by Django 3.0.7 on 2020-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_auto_20200829_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_participants',
            field=models.PositiveIntegerField(default=10, help_text='Overrides any value set on individual linked events'),
        ),
    ]
