# Generated by Django 3.0.7 on 2020-09-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_auto_20200901_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_partial_booking',
            field=models.BooleanField(default=False, help_text='Users can book after a course has started (if they have purchased a credit block valid for the remaining number of classes)'),
        ),
    ]
