# Generated by Django 3.0.10 on 2020-10-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_booking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='maximum_age_for_booking',
            field=models.PositiveIntegerField(blank=True, help_text="Maximum age allowed for booking (inclusive - i.e. 16 allows booking up to the student's 17th birthday)", null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='minimum_age_for_booking',
            field=models.PositiveIntegerField(blank=True, help_text="Minimum age allowed for booking (inclusive - i.e. 16 allows booking from the student's 16th birthday)", null=True),
        ),
    ]
