# Generated by Django 3.0.10 on 2020-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_auto_20201015_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevoucher',
            name='temp_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
