# Generated by Django 3.0.10 on 2020-11-09 14:08

from django.db import migrations


def copy_codes(apps, schema_editor):
    BlockVoucher = apps.get_model('booking', 'BlockVoucher')
    for voucher in BlockVoucher.objects.all():
        voucher.temp_code = voucher.code
        voucher.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_basevoucher_temp_code'),
    ]

    operations = [
        migrations.RunPython(copy_codes, reverse_code=migrations.RunPython.noop)
    ]
