# Generated by Django 3.0.10 on 2020-11-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_move_existing_voucher_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockvoucher',
            name='code',
        ),
    ]
