# Generated by Django 3.0.10 on 2020-11-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_remove_blockvoucher_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basevoucher',
            old_name='temp_code',
            new_name='code',
        ),
    ]
