# Generated by Django 3.0.10 on 2020-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_auto_20201109_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basevoucher',
            name='code',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
