# Generated by Django 3.0.10 on 2020-11-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_auto_20201109_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalVoucher',
            fields=[
                ('basevoucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.BaseVoucher')),
            ],
            bases=('booking.basevoucher',),
        ),
    ]
