# Generated by Django 3.0.10 on 2020-12-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_totalvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_link_available_after_class',
            field=models.BooleanField(default=False, help_text='Zoom/Video URL available after class is past (for online classes only)'),
        ),
    ]
