# Generated by Django 3.0.7 on 2020-09-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_totalvoucher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GiftVoucherType',
            new_name='GiftVoucher',
        ),
    ]
