# Generated by Django 3.0.10 on 2020-12-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_rename_gift_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Exact amount discount'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='active',
            field=models.BooleanField(default=True, help_text='Display on site; set to False instead of deleting unused gift vouchers'),
        ),
    ]
