# Generated by Django 3.2.6 on 2021-08-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_auto_20201228_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionconfig',
            name='bookable_event_types',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
