# Generated by Django 3.0.10 on 2020-12-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20201109_1614'),
        ('booking', '0049_auto_20201222_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftvoucher',
            name='active',
        ),
        migrations.RemoveField(
            model_name='giftvoucher',
            name='block_config',
        ),
        migrations.RemoveField(
            model_name='giftvoucher',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='block_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.BlockVoucher'),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_vouchers', to='payments.Invoice'),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='total_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.TotalVoucher'),
        ),
        migrations.CreateModel(
            name='GiftVoucherConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Exact amount discount')),
                ('active', models.BooleanField(default=True, help_text='Display on site; set to False instead of deleting unused gift vouchers')),
                ('block_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_vouchers', to='booking.BlockConfig')),
            ],
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='gift_voucher_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.GiftVoucherConfig'),
            preserve_default=False,
        ),
    ]
