# Generated by Django 3.0.10 on 2021-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_auto_20201228_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
