# Generated by Django 4.0.3 on 2022-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_alter_subscriptionconfig_bookable_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_drop_in',
            field=models.BooleanField(default=False, help_text='Users can book individual events with a drop-in credit block valid for this event type'),
        ),
    ]
