# Generated by Django 3.0.10 on 2021-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_add_product_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'product categories'},
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name_plural': 'product stock'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='active',
            field=models.BooleanField(default=True, help_text='Visible on site and available to purchase'),
        ),
    ]
