# Generated by Django 3.0.10 on 2020-12-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_auto_20201223_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
