# Generated by Django 3.0.10 on 2020-12-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_giftvoucher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftvoucher',
            name='block_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_voucher', to='booking.BlockVoucher'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='total_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_voucher', to='booking.TotalVoucher'),
        ),
    ]
