# Generated by Django 4.0.3 on 2022-08-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_course_allow_drop_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockvoucher',
            name='item_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Required number of items that must be purchased at one time with this voucher. Set to 1 if the voucher applies to a single purchased block/course.  Set to more than 1 if it ONLY applies if the user purchases a set number of items (e.g. if you want a 10% discount when a user purchases 2 blocks/courses at a time', null=True, verbose_name='Number of items'),
        ),
    ]
