# Generated by Django 3.0.10 on 2021-08-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_auto_20210822_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', 'name')},
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='booking.ProductVariant'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
    ]
