# Generated by Django 3.0.10 on 2020-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_auto_20201226_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucherconfig',
            name='duration',
            field=models.PositiveIntegerField(default=6, help_text='How many months will this gift voucher last?'),
        ),
    ]
