# Generated by Django 4.1.1 on 2022-10-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0052_blockvoucher_item_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="allow_partial_booking",
        ),
        migrations.AlterField(
            model_name="blockvoucher",
            name="item_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="Required number of items that must be purchased at one time with this voucher. Set to 1 if the voucher applies to a single purchased block/course.  Set to more than 1 if it ONLY applies if the user purchases a set number of items (e.g. if you want a 10% discount when a user purchases 2 blocks/courses at a time)",
                null=True,
                verbose_name="Number of items",
            ),
        ),
    ]
