# Generated by Django 3.0.10 on 2021-08-22 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_auto_20210822_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='date_purchased',
            new_name='date_paid',
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
