# Generated by Django 4.1.1 on 2022-10-10 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0053_remove_course_allow_partial_booking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
