# Generated by Django 3.0.10 on 2021-08-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_auto_20210822_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Visible on site and available to purchase'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='booking.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='size',
            field=models.CharField(default='XS', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
