# Generated by Django 4.1.1 on 2022-10-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0054_block_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="time_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
