# Generated by Django 3.0.10 on 2021-08-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_auto_20210823_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-active', 'category', 'name')},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'product categories'},
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='date_paid',
            field=models.DateTimeField(blank=True, help_text='Leave blank for today', null=True),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='date_received',
            field=models.DateTimeField(blank=True, help_text='Leave blank for today', null=True),
        ),
    ]
