# Generated by Django 4.1.1 on 2022-10-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0055_block_time_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockconfig",
            name="disabled",
            field=models.BooleanField(default=False, help_text="Not visible or usable"),
        ),
    ]
