# Generated by Django 3.2.6 on 2021-08-29 08:21

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_stripepaymentintent_metadata'),
        ('merchandise', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_purchases', to='payments.invoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='merchandise'),
        ),
    ]
