# Generated by Django 3.2.6 on 2021-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_auto_20210829_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
