# Generated by Django 3.2.6 on 2021-09-03 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchandise', '0005_productpurchase_time_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='auth.user'),
            preserve_default=False,
        ),
    ]
