# Generated by Django 3.0.7 on 2020-07-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0017_auto_20200716_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.EventType')),
            ],
        ),
    ]
