# Generated by Django 3.0.7 on 2020-07-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesession',
            name='duration',
            field=models.PositiveIntegerField(default=90, help_text='Duration in minutes'),
        ),
    ]
